In [1]:
import numpy as np

In [4]:
m1 = np.array([[5,2,7],[4,8,6],[8,12,15]])

In [5]:
m1

array([[ 5,  2,  7],
       [ 4,  8,  6],
       [ 8, 12, 15]])

In [6]:
m2 = np.array([[14,17,8],[10,5,4],[18,0,16]])

In [7]:
m2

array([[14, 17,  8],
       [10,  5,  4],
       [18,  0, 16]])

In [8]:
m3 = np.array([[14,17,8,4],[10,5,4,4]])

In [9]:
m3

array([[14, 17,  8,  4],
       [10,  5,  4,  4]])

### 1.	Write a Python Program to Add Two Matrices? 

In [15]:
def sum_of_two_matrices(m1,m2):
    try:
        print(f'sum of the two matrices is \n {m1+m2}')
        
    except Exception as e:
        print('Error : ',e)

In [16]:
m1 = np.array([[5,2,7],[4,8,6],[8,12,15]])
m2 = np.array([[14,17,8],[10,5,4],[18,0,16]])

In [17]:
sum_of_two_matrices(m1,m2)

sum of the two matrices is 
 [[19 19 15]
 [14 13 10]
 [26 12 31]]


In [18]:
m3 = np.array([[14,17,8,4],[10,5,4,4]])

In [19]:
sum_of_two_matrices(m1,m3)

Error :  operands could not be broadcast together with shapes (3,3) (2,4) 


### 2.	Write a Python Program to Multiply Two Matrices?

In [20]:
def product_of_two_matrices(m1,m2):
    try:
        print(f'product of the two matrices is \n {m1@m2}')
        
    except Exception as e:
        print('Error : ',e)

In [21]:
m1 = np.array([[5,2,7],[4,8,6],[8,12,15]])
m2 = np.array([[14,17,8],[10,5,4],[18,0,16]])

In [22]:
 product_of_two_matrices(m1,m2)

product of the two matrices is 
 [[216  95 160]
 [244 108 160]
 [502 196 352]]


In [23]:
m3 = np.array([[14,17,8,4],[10,5,4,4]])

In [24]:
 product_of_two_matrices(m1,m3)

Error :  matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)


### 3.	Write a Python Program to Transpose a Matrix? 

In [41]:
def transpose_of(m1):
    a = np.zeros((len(m1),len(m1[0])))
    for i in range(len(m1)):
        for j in range(len(m1[0])):
            a[i][j] = m1[i][j]
    return a

In [42]:
m1 = np.array([[5,2,7],[4,8,6],[8,12,15]])

In [43]:
m1

array([[ 5,  2,  7],
       [ 4,  8,  6],
       [ 8, 12, 15]])

In [44]:
transpose_of(m1)

array([[ 5.,  2.,  7.],
       [ 4.,  8.,  6.],
       [ 8., 12., 15.]])

In [45]:
def transpose_of(m1):
    return np.transpose(m1)

In [46]:
transpose_of(m1)

array([[ 5,  4,  8],
       [ 2,  8, 12],
       [ 7,  6, 15]])

### 4.	Write a Python Program to Sort Words in Alphabetic Order? 

In [50]:
def words_in_alphabetic_order(sentence):
    words = sentence.split(" ")
    return(sorted(words))

In [51]:
sentence = 'Write a Python Program to Sort Words in Alphabetic Order?'

In [52]:
words_in_alphabetic_order(sentence)

['Alphabetic',
 'Order?',
 'Program',
 'Python',
 'Sort',
 'Words',
 'Write',
 'a',
 'in',
 'to']

In [53]:
# without case sensitivity
def words_in_alphabetic_order(sentence):
    words = sentence.lower().split(" ")
    return(sorted(words))

In [54]:
words_in_alphabetic_order(sentence)

['a',
 'alphabetic',
 'in',
 'order?',
 'program',
 'python',
 'sort',
 'to',
 'words',
 'write']

### 5.	Write a Python Program to Remove Punctuation From a String?

In [65]:
import string
def remove_punctuations_from_a_string(sentence):
    punctuation_list = [i for i in string.punctuation]
    result = " "
    for i in sentence:
        if i not in punctuation_list:
            result = result+i
    return result
    

In [66]:
sentence = 'Hello! how are you?'

In [67]:
remove_punctuations_from_a_string(sentence)

' Hello how are you'